### PR TITLE
Fix for Issue #32

### PR DESCRIPTION
**Pull request by sjalloq**
- in uvm_reg_map.py, the list returned by Xget_bus_infoX() should overwrite
   the same variables passed in.

### CODE REVIEW

**Comment by sjalloq** [comment]
This is my initial attempt at fixing this bug.  Need some feedback on how byte_en should be treated before merging this.

**Comment by tpoikela** [comment]
This looks like a copy-paste error from the `return [...]` of `Xget_bus_infoX( )`. Thanks for the fix!

**Comment by tpoikela** [comment]
I think further development could be to add this as a static function in `class sv`. Something along lines:

```
class sv:
...
  def get_vector_of_ones(cls, width):
    return int(''.join(['1' for bit in range(width)]),2)
```

**Comment by sjalloq** [comment]
Hi, agree that moving that not very intuitive snippet into the `sv` class is a good idea.

**Pull request merged**
