### PR TITLE
Initial TLM2 Implementation

### PR DESCRIPTION
**Pull request by mballance**
I've completed conversion of the TLM2 classes and have the simple 'blocking' example running

### CODE REVIEW

**Comment by mballance** [comment]
Hi Tuomas,
    Looks like this PR and commits from you in the TLM2 area came in around the same time. I'll be happy to re-merge this PR with 'master' to resolve the conflicts if you'd like.

Thanks,
Matthew

**Comment by tpoikela** [comment]
Hi Matthew

Yes, that would be perfect if you can merge. I saw that you had done much
more work than I did for TLM2, so you can most likely override many, if not
all, my changes.

-Tuomas

**Comment by mballance** [comment]
Okay, I've completed the merge and the test still runs. One difference in our conversion is that I used UVMTlm, while you used UVMTLM. I resolved the difference in favor of the naming convention I used (UVMTlm...). Let me know if you'd like to go the other direction.

Thanks,
Matthew

**Comment by tpoikela** [comment]
We should just make sure each class is named in similar fashion. I used
UVMTLM in TLM1 classes, so let us go with that naming for now. It is lot of
capital letters, especially in UVMTLMFIFO.

ti 11. helmik. 2020 klo 5.01 Matthew Ballance <notifications@github.com>
kirjoitti:

**Comment by mballance** [comment]
Hey Tuomas, just sent a PR your way to rename the UVMTlm classes to UVMTLM.

**Comment by cmarqu** [comment]
Awesome!
The README still only talks about TLM 1.0 though.

**Comment by tpoikela** [comment]
Thanks for pointing out. To be updated soon. Also with minimal running
example without simulator.

pe 14. helmik. 2020 klo 12.49 Colin Marquardt <notifications@github.com>
kirjoitti:

**Pull request merged**
